# Sales Forecasting

In [1]:
import pandas as pd
from prophet import Prophet

In [2]:
df =pd.read_csv('..\data\clean_sales.csv')

In [3]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [4]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
392687,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
392688,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
392689,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
392690,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
392691,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [5]:
sales = df.groupby('InvoiceDate')['TotalPrice'].sum().reset_index()
sales

              InvoiceDate  TotalPrice
0     2010-12-01 08:26:00      139.12
1     2010-12-01 08:28:00       22.20
2     2010-12-01 08:34:00      348.78
3     2010-12-01 08:35:00       17.85
4     2010-12-01 08:45:00      855.86
...                   ...         ...
17277 2011-12-09 12:23:00      124.60
17278 2011-12-09 12:25:00      140.64
17279 2011-12-09 12:31:00      329.05
17280 2011-12-09 12:49:00      339.20
17281 2011-12-09 12:50:00      249.45

[17282 rows x 2 columns]

In [6]:
sales['Date'] = sales['InvoiceDate'].dt.date
sales.drop(columns= "InvoiceDate",inplace = True)
sales

       TotalPrice        Date
0          139.12  2010-12-01
1           22.20  2010-12-01
2          348.78  2010-12-01
3           17.85  2010-12-01
4          855.86  2010-12-01
...           ...         ...
17277      124.60  2011-12-09
17278      140.64  2011-12-09
17279      329.05  2011-12-09
17280      339.20  2011-12-09
17281      249.45  2011-12-09

[17282 rows x 2 columns]

In [7]:
sales = sales.groupby('Date')['TotalPrice'].sum().reset_index()

In [8]:
sales

           Date  TotalPrice
0    2010-12-01    46192.49
1    2010-12-02    47197.57
2    2010-12-03    23876.63
3    2010-12-05    31361.28
4    2010-12-06    31009.33
..          ...         ...
300  2011-12-05    58081.09
301  2011-12-06    45989.66
302  2011-12-07    69230.60
303  2011-12-08    50395.96
304  2011-12-09   184329.66

[305 rows x 2 columns]

In [9]:
sales.columns = ['ds', 'y']

In [10]:
model = Prophet()
model.fit(sales)

14:08:55 - cmdstanpy - INFO - Chain [1] start processing
14:08:56 - cmdstanpy - INFO - Chain [1] done processing

In [11]:
future = model.make_future_dataframe(periods = 90)
forecast = model.predict(future)

In [12]:
forecast

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2010-12-01,24751.298271,5557.313118,41633.045016,24751.298271,24751.298271,-739.645791,-739.645791,-739.645791,-739.645791,-739.645791,-739.645791,0.0,0.0,0.0,24011.652480
1,2010-12-02,24749.175113,12949.526324,49654.218754,24749.175113,24749.175113,6528.733703,6528.733703,6528.733703,6528.733703,6528.733703,6528.733703,0.0,0.0,0.0,31277.908815
2,2010-12-03,24747.051954,4622.156660,40772.145230,24747.051954,24747.051954,-1465.873269,-1465.873269,-1465.873269,-1465.873269,-1465.873269,-1465.873269,0.0,0.0,0.0,23281.178685
3,2010-12-05,24742.805637,-9380.354172,26809.146558,24742.805637,24742.805637,-15025.016496,-15025.016496,-15025.016496,-15025.016496,-15025.016496,-15025.016496,0.0,0.0,0.0,9717.789141
4,2010-12-06,24740.682478,5953.608387,41131.385378,24740.682478,24740.682478,-1981.877225,-1981.877225,-1981.877225,-1981.877225,-1981.877225,-1981.877225,0.0,0.0,0.0,22758.805254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,2012-03-04,69399.101252,37334.099462,72369.782112,67895.681754,70906.254064,-15025.016496,-15025.016496,-15025.016496,-15025.016496,-15025.016496,-15025.016496,0.0,0.0,0.0,54374.084756
391,2012-03-05,69593.894112,50430.717932,86815.576047,68064.046913,71127.524563,-1981.877225,-1981.877225,-1981.877225,-1981.877225,-1981.877225,-1981.877225,0.0,0.0,0.0,67612.016888
392,2012-03-06,69788.686972,53714.592575,89570.833960,68236.422269,71350.056675,1986.147085,1986.147085,1986.147085,1986.147085,1986.147085,1986.147085,0.0,0.0,0.0,71774.834057
393,2012-03-07,69983.479832,51286.085305,86738.981269,68405.085793,71562.223029,-739.645791,-739.645791,-739.645791,-739.645791,-739.645791,-739.645791,0.0,0.0,0.0,69243.834041
394,2012-03-08,70178.272692,60519.409020,95363.400894,68578.842656,71794.317227,6528.733703,6528.733703,6528.733703,6528.733703,6528.733703,6528.733703,0.0,0.0,0.0,76707.006395

In [13]:
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].to_csv('..\data\sales_forecast.csv', index = False)
print("Sales forecasting complete. Saved to ..\data\sales_forecast.csv")

Sales forecasting complete. Saved to ..\data\sales_forecast.csv